[servers]
"@modelcontextprotocol/server-filesystem" = { command = "npx", args = ["-y", "@modelcontextprotocol/server-filesystem"] }
test-server = { command = "npx" }
postgres = { command = "npx", args = ["-y", "@modelcontextprotocol/server-postgres"], env = { POSTGRES_DB = "mydb" } }
